"""WeakNet Lab command-line orchestration.

All network mutation is restricted to names generated by ``ResourceNames``.
The daemon, diagnosis engines, D-Bus service, and CLI are the real built
products; this module never injects incidents or hypotheses.
"""

from __future__ import annotations

import argparse
import asyncio
from dataclasses import dataclass
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import os
from pathlib import Path
import re
import secrets
import signal
import subprocess
import sys
import threading
import time
from typing import Any, Mapping, Sequence
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from .model import (
    AI_MODES,
    CapabilityReport,
    Scenario,
    detect_capabilities,
    evaluate_diagnosis,
    load_scenario,
    missing_capabilities,
    public_doctor_lines,
    skipped_evaluation,
    validate_evaluation,
)


ROOT = Path(__file__).resolve().parents[2]
LAB_ROOT = ROOT / "lab"
SCENARIO_ROOT = LAB_ROOT / "scenarios"
STATE_ROOT = LAB_ROOT / ".state"
OUTPUT_ROOT = LAB_ROOT / "output"
ACTIVE_STATE = STATE_ROOT / "active.json"
OWNED_NAMESPACE = re.compile(r"^wnlab-[cs]-[0-9a-f]{6}$")
OWNED_INTERFACE = re.compile(r"^wn[cs]-[0-9a-f]{6}$")
TCP_PORT = 18080
VERBOSE = False


class LabError(RuntimeError):
    pass


class CommandTimedOut(LabError):
    pass


def _debug(message: str) -> None:
    if VERBOSE:
        print(f"[debug] {message}")


@dataclass(frozen=True)
class ResourceNames:
    token: str
    client_namespace: str
    server_namespace: str
    client_interface: str
    server_interface: str

    @classmethod
    def create(cls, token: str | None = None) -> "ResourceNames":
        value = token or secrets.token_hex(3)
        if not re.fullmatch(r"[0-9a-f]{6}", value):
            raise ValueError("resource token must contain six lowercase hex characters")
        return cls(
            token=value,
            client_namespace=f"wnlab-c-{value}",
            server_namespace=f"wnlab-s-{value}",
            client_interface=f"wnc-{value}",
            server_interface=f"wns-{value}",
        )

    @classmethod
    def from_state(cls, value: Mapping[str, Any]) -> "ResourceNames":
        result = cls(
            token=str(value.get("token", "")),
            client_namespace=str(value.get("client_namespace", "")),
            server_namespace=str(value.get("server_namespace", "")),
            client_interface=str(value.get("client_interface", "")),
            server_interface=str(value.get("server_interface", "")),
        )
        result.validate()
        return result

    def validate(self) -> None:
        if not re.fullmatch(r"[0-9a-f]{6}", self.token):
            raise LabError("refusing cleanup for an invalid lab token")
        if not OWNED_NAMESPACE.fullmatch(self.client_namespace) or not OWNED_NAMESPACE.fullmatch(
            self.server_namespace
        ):
            raise LabError("refusing cleanup for a non-lab namespace")
        if not OWNED_INTERFACE.fullmatch(self.client_interface) or not OWNED_INTERFACE.fullmatch(
            self.server_interface
        ):
            raise LabError("refusing cleanup for a non-lab interface")
        expected = ResourceNames.create(self.token)
        if self != expected:
            raise LabError("lab resource names do not share one ownership token")

    def to_dict(self) -> dict[str, str]:
        return {
            "token": self.token,
            "client_namespace": self.client_namespace,
            "server_namespace": self.server_namespace,
            "client_interface": self.client_interface,
            "server_interface": self.server_interface,
        }


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def run_bounded(
    command: Sequence[str], *, timeout: float = 10, check: bool = True,
    env: Mapping[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    try:
        result = subprocess.run(
            list(command), check=False, capture_output=True, text=True,
            timeout=timeout, env=dict(env) if env is not None else None,
        )
    except subprocess.TimeoutExpired as error:
        raise CommandTimedOut(f"command timed out after {timeout:g}s: {command[0]}") from error
    if check and result.returncode != 0:
        detail = (result.stderr or result.stdout).strip().splitlines()
        message = detail[-1] if detail else f"exit {result.returncode}"
        raise LabError(f"command failed: {command[0]}: {message}")
    return result


def _process_start_time(pid: int) -> str | None:
    try:
        return Path(f"/proc/{pid}/stat").read_text(encoding="utf-8").split()[21]
    except (OSError, IndexError):
        return None


def _same_process(pid: int, start_time: str | None) -> bool:
    return start_time is not None and _process_start_time(pid) == start_time


def _stop_owned_process(record: Mapping[str, Any], timeout: float = 3) -> None:
    try:
        pid = int(record["pid"])
        start_time = str(record["start_time"])
    except (KeyError, TypeError, ValueError):
        return
    if not _same_process(pid, start_time):
        return
    try:
        os.killpg(pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        return
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if not _same_process(pid, start_time):
            return
        time.sleep(0.05)
    if _same_process(pid, start_time):
        try:
            os.killpg(pid, signal.SIGKILL)
        except (ProcessLookupError, PermissionError):
            pass


def _atomic_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)


def _load_state(path: Path = ACTIVE_STATE) -> dict[str, Any] | None:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None
    except (OSError, json.JSONDecodeError) as error:
        raise LabError(f"cannot read lab state: {error}") from error
    if not isinstance(value, dict):
        raise LabError("lab state is not an object")
    ResourceNames.from_state(value.get("resources", {}))
    return value


def _privilege_prefix(report: CapabilityReport) -> list[str]:
    if os.geteuid() == 0 or report.privilege_reason.startswith("effective"):
        return []
    if report.privilege_reason == "passwordless sudo available":
        return ["sudo", "-n"]
    raise LabError(report.privilege_reason)


def _privileged(report: CapabilityReport, command: Sequence[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
    return run_bounded([*_privilege_prefix(report), *command], **kwargs)


def _netns_command(report: CapabilityReport, namespace: str, command: Sequence[str]) -> list[str]:
    if not OWNED_NAMESPACE.fullmatch(namespace):
        raise LabError("refusing to enter a non-lab namespace")
    return [*_privilege_prefix(report), "ip", "netns", "exec", namespace, *command]


def _start_process(
    command: Sequence[str], log_path: Path, *, env: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    stream = log_path.open("ab", buffering=0)
    try:
        process = subprocess.Popen(
            list(command), stdin=subprocess.DEVNULL, stdout=stream, stderr=subprocess.STDOUT,
            env=dict(env) if env is not None else None, start_new_session=True,
        )
    finally:
        stream.close()
    start_time = _process_start_time(process.pid)
    if start_time is None:
        raise LabError(f"failed to track process: {command[0]}")
    _debug(f"started {Path(command[0]).name} pid={process.pid} log={log_path}")
    return {"pid": process.pid, "start_time": start_time, "command": Path(command[0]).name}


def _record_process(state: dict[str, Any], name: str, record: Mapping[str, Any]) -> None:
    state.setdefault("processes", {})[name] = dict(record)
    _atomic_json(ACTIVE_STATE, state)


def _scenario_path(scenario_id: str) -> Path:
    if not re.fullmatch(r"[a-z0-9-]+", scenario_id):
        raise LabError("invalid scenario ID")
    path = SCENARIO_ROOT / f"{scenario_id}.json"
    if not path.is_file():
        raise LabError(f"unknown scenario: {scenario_id}")
    return path


def scenarios() -> list[Scenario]:
    return [load_scenario(path) for path in sorted(SCENARIO_ROOT.glob("*.json"))]


def _lab_addresses(token: str) -> tuple[str, str, str]:
    octet = 64 + (int(token[:2], 16) % 128)
    return f"198.18.{octet}.1", f"198.18.{octet}.2", f"198.18.{octet}.0/30"


def _wait_for(predicate: Any, timeout: float, description: str, interval: float = 0.1) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if predicate():
            return
        time.sleep(interval)
    raise LabError(f"timed out waiting for {description}")


def _start_bus(state: dict[str, Any], run_root: Path) -> str:
    socket_path = run_root / "bus.sock"
    address = f"unix:path={socket_path}"
    record = _start_process(
        ["dbus-daemon", "--session", "--nofork", f"--address={address}", "--nopidfile"],
        run_root / "dbus.log",
    )
    _record_process(state, "dbus", record)
    _wait_for(socket_path.exists, 5, "lab session D-Bus socket")
    state["bus_address"] = address
    _atomic_json(ACTIVE_STATE, state)
    return address


def _setup_topology(state: dict[str, Any], report: CapabilityReport) -> None:
    resources = ResourceNames.from_state(state["resources"])
    client_ip, server_ip, subnet = _lab_addresses(resources.token)
    state["addresses"] = {"client": client_ip, "server": server_ip, "subnet": subnet}
    _atomic_json(ACTIVE_STATE, state)
    prefix = _privilege_prefix(report)
    commands = [
        [*prefix, "ip", "netns", "add", resources.client_namespace],
        [*prefix, "ip", "netns", "add", resources.server_namespace],
        [*prefix, "ip", "link", "add", resources.client_interface, "type", "veth", "peer", "name", resources.server_interface],
        [*prefix, "ip", "link", "set", resources.client_interface, "netns", resources.client_namespace],
        [*prefix, "ip", "link", "set", resources.server_interface, "netns", resources.server_namespace],
        [*prefix, "ip", "-n", resources.client_namespace, "link", "set", "lo", "up"],
        [*prefix, "ip", "-n", resources.server_namespace, "link", "set", "lo", "up"],
        [*prefix, "ip", "-n", resources.client_namespace, "addr", "add", f"{client_ip}/30", "dev", resources.client_interface],
        [*prefix, "ip", "-n", resources.server_namespace, "addr", "add", f"{server_ip}/30", "dev", resources.server_interface],
        [*prefix, "ip", "-n", resources.client_namespace, "link", "set", resources.client_interface, "up"],
        [*prefix, "ip", "-n", resources.server_namespace, "link", "set", resources.server_interface, "up"],
        [*prefix, "ip", "-n", resources.client_namespace, "route", "add", "default", "via", server_ip, "dev", resources.client_interface],
    ]
    for command in commands:
        run_bounded(command, timeout=10)


def _daemon_environment(state: Mapping[str, Any], run_root: Path) -> list[str]:
    return [
        "/usr/bin/env",
        f"DBUS_SESSION_BUS_ADDRESS={state['bus_address']}",
        f"WEAKNET_STATE_DIR={run_root / 'daemon-state'}",
        f"WEAKNET_LOG_DIR={run_root / 'daemon-logs'}",
        f"WEAKNET_RUNTIME_DIR={run_root / 'daemon-run'}",
    ]


def _start_product(state: dict[str, Any], report: CapabilityReport, run_root: Path) -> None:
    resources = ResourceNames.from_state(state["resources"])
    for name in ("daemon-state", "daemon-logs", "daemon-run"):
        path = run_root / name
        path.mkdir(parents=True, exist_ok=True)
        path.chmod(0o777)
    server_ready = run_root / "server.ready"
    server = _start_process(
        _netns_command(report, resources.server_namespace, [
            sys.executable, str(LAB_ROOT / "helpers" / "tcp_server.py"),
            "--bind", state["addresses"]["server"], "--port", str(TCP_PORT),
            "--ready-file", str(server_ready),
        ]),
        run_root / "tcp-server.log",
    )
    _record_process(state, "tcp_server", server)
    _wait_for(server_ready.exists, 5, "TCP workload server")
    daemon_command = _netns_command(
        report, resources.client_namespace,
        [*_daemon_environment(state, run_root), str(report.weaknetd_path)],
    )
    daemon = _start_process(daemon_command, run_root / "weaknetd.log")
    _record_process(state, "weaknetd", daemon)
    cli_env = dict(os.environ)
    cli_env["DBUS_SESSION_BUS_ADDRESS"] = str(state["bus_address"])
    _wait_for(
        lambda: run_bounded([str(report.weaknetctl_path), "status"], check=False, env=cli_env, timeout=3).returncode in (0, 1, 2),
        8,
        "weaknetd D-Bus service",
        interval=0.2,
    )


def _start_workload(state: dict[str, Any], report: CapabilityReport, run_root: Path) -> None:
    resources = ResourceNames.from_state(state["resources"])
    client = _start_process(
        _netns_command(report, resources.client_namespace, [
            sys.executable, str(LAB_ROOT / "helpers" / "tcp_load.py"),
            "--host", state["addresses"]["server"], "--port", str(TCP_PORT),
        ]),
        run_root / "tcp-load.log",
    )
    _record_process(state, "tcp_load", client)


def _apply_fault(state: Mapping[str, Any], report: CapabilityReport, scenario: Scenario) -> None:
    resources = ResourceNames.from_state(state["resources"])
    prefix = _privilege_prefix(report)
    if scenario.fault == "none":
        _debug("no fault requested")
        return
    _debug(f"applying {scenario.fault} inside {resources.server_namespace if scenario.fault.startswith('netem-') else resources.client_namespace}")
    if scenario.fault == "netem-delay":
        delay = int(scenario.fault_options.get("delay_ms", 0))
        if not 1 <= delay <= 5000:
            raise LabError("netem delay must be between 1 and 5000 ms")
        run_bounded([*prefix, "ip", "netns", "exec", resources.server_namespace,
                     "tc", "qdisc", "replace", "dev", resources.server_interface,
                     "root", "netem", "delay", f"{delay}ms"])
    elif scenario.fault == "netem-loss":
        loss = int(scenario.fault_options.get("loss_percent", 0))
        if not 1 <= loss <= 80:
            raise LabError("netem loss must be between 1 and 80 percent")
        run_bounded([*prefix, "ip", "netns", "exec", resources.server_namespace,
                     "tc", "qdisc", "replace", "dev", resources.server_interface,
                     "root", "netem", "loss", f"{loss}%"])
    elif scenario.fault == "remove-default-route":
        run_bounded([*prefix, "ip", "-n", resources.client_namespace, "route", "del",
                     "default", "via", state["addresses"]["server"], "dev",
                     resources.client_interface])
    else:
        raise LabError(f"unsupported fault: {scenario.fault}")


def _remove_fault(state: Mapping[str, Any], report: CapabilityReport, scenario: Scenario) -> None:
    resources = ResourceNames.from_state(state["resources"])
    prefix = _privilege_prefix(report)
    if scenario.fault.startswith("netem-"):
        run_bounded([*prefix, "ip", "netns", "exec", resources.server_namespace,
                     "tc", "qdisc", "del", "dev", resources.server_interface, "root"],
                    check=False)
    elif scenario.fault == "remove-default-route":
        run_bounded([*prefix, "ip", "-n", resources.client_namespace, "route", "replace",
                     "default", "via", state["addresses"]["server"], "dev",
                     resources.client_interface])


def _capture_diagnosis(state: Mapping[str, Any]) -> dict[str, Any]:
    previous = os.environ.get("DBUS_SESSION_BUS_ADDRESS")
    os.environ["DBUS_SESSION_BUS_ADDRESS"] = str(state["bus_address"])
    try:
        from ai.v2.sources.dbus import DbusDiagnosisSource
        snapshot = asyncio.run(DbusDiagnosisSource(timeout_seconds=3).current())
        return snapshot.to_dict()
    finally:
        if previous is None:
            os.environ.pop("DBUS_SESSION_BUS_ADDRESS", None)
        else:
            os.environ["DBUS_SESSION_BUS_ADDRESS"] = previous


def _diagnosis_matches(scenario: Scenario, diagnosis: Mapping[str, Any]) -> bool:
    observed_incidents = {
        item.get("type") for item in diagnosis.get("incidents", []) if isinstance(item, Mapping)
    }
    observed_hypotheses = {
        item.get("type") for item in diagnosis.get("hypotheses", []) if isinstance(item, Mapping)
    }
    return (
        set(scenario.expected_incidents).issubset(observed_incidents)
        and set(scenario.expected_hypothesis_types).issubset(observed_hypotheses)
        and not (observed_hypotheses - set(scenario.allowed_hypothesis_types))
        and diagnosis.get("status") in scenario.allowed_statuses
        and (not scenario.require_nonhealthy_status or diagnosis.get("status") != "Healthy")
    )


def _wait_for_diagnosis(state: Mapping[str, Any], scenario: Scenario) -> tuple[dict[str, Any], int | None]:
    started = time.monotonic()
    if not scenario.expected_incidents and not scenario.expected_hypothesis_types:
        time.sleep(scenario.observation_timeout_seconds)
        return _capture_diagnosis(state), int((time.monotonic() - started) * 1000)
    deadline = started + scenario.observation_timeout_seconds
    last: dict[str, Any] | None = None
    while time.monotonic() < deadline:
        last = _capture_diagnosis(state)
        if _diagnosis_matches(scenario, last):
            return last, int((time.monotonic() - started) * 1000)
        time.sleep(1)
    return last or _capture_diagnosis(state), None


def _wait_for_recovery(state: Mapping[str, Any], scenario: Scenario) -> tuple[bool, int | None]:
    started = time.monotonic()
    deadline = started + scenario.recovery_timeout_seconds
    while time.monotonic() < deadline:
        diagnosis = _capture_diagnosis(state)
        incidents = {
            item.get("type") for item in diagnosis.get("incidents", []) if isinstance(item, Mapping)
        }
        hypotheses = {
            item.get("type") for item in diagnosis.get("hypotheses", []) if isinstance(item, Mapping)
        }
        if not (set(scenario.expected_incidents) & incidents) and not (
            set(scenario.expected_hypothesis_types) & hypotheses
        ):
            return True, int((time.monotonic() - started) * 1000)
        time.sleep(1)
    return False, None


def _cli(state: Mapping[str, Any], report: CapabilityReport, *arguments: str) -> subprocess.CompletedProcess[str]:
    environment = dict(os.environ)
    environment["DBUS_SESSION_BUS_ADDRESS"] = str(state["bus_address"])
    if state.get("ai_port"):
        environment["WEAKNET_AI_PORT"] = str(state["ai_port"])
    return run_bounded(
        [str(report.weaknetctl_path), *arguments], check=False, env=environment, timeout=45,
    )


def _start_ai_runtime(state: dict[str, Any], report: CapabilityReport, run_root: Path) -> tuple[bool, str]:
    provider = os.environ.get("WEAKNET_LLM_PROVIDER", "").lower()
    if not provider:
        return False, "WEAKNET_LLM_PROVIDER is not configured"
    if provider == "dashscope" and not os.environ.get("DASHSCOPE_API_KEY"):
        return False, "DashScope API key is not configured"
    if not report.python_venv or not report.dbus_next:
        return False, "repository .venv runtime dependencies are unavailable"
    port = 18000 + (int(ResourceNames.from_state(state["resources"]).token[:4], 16) % 2000)
    environment = dict(os.environ)
    environment["DBUS_SESSION_BUS_ADDRESS"] = str(state["bus_address"])
    environment["WEAKNET_AI_PORT"] = str(port)
    record = _start_process(
        [str(ROOT / ".venv" / "bin" / "python"), "-m", "ai.v2.runtime"],
        run_root / "ai-runtime.log", env=environment,
    )
    _record_process(state, "ai_runtime", record)
    state["ai_runtime_port"] = port
    _atomic_json(ACTIVE_STATE, state)

    def healthy() -> bool:
        try:
            with urlopen(f"http://127.0.0.1:{port}/health/live", timeout=0.3) as response:
                return response.status == 200
        except OSError:
            return False

    _wait_for(healthy, 8, "AI runtime")
    return True, ""


def _run_cli_with_ai_capture(
    state: dict[str, Any], report: CapabilityReport, mode: str,
) -> tuple[subprocess.CompletedProcess[str], int, dict[str, Any]]:
    capture: dict[str, Any] = {}
    upstream_port = int(state["ai_runtime_port"])
    expected_path = "/v2/explanations/current" if mode == "explain" else "/v2/advice/current"

    class RecordingProxy(BaseHTTPRequestHandler):
        def do_POST(self) -> None:  # noqa: N802 - stdlib handler API
            try:
                length = int(self.headers.get("Content-Length", "0"))
            except ValueError:
                length = -1
            if self.path != expected_path or not 0 <= length <= 1_048_576:
                self.send_error(400)
                return
            request = Request(
                f"http://127.0.0.1:{upstream_port}{self.path}",
                data=self.rfile.read(length),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            try:
                with urlopen(request, timeout=45) as response:
                    status = int(response.status)
                    body = response.read()
            except HTTPError as error:
                status = int(error.code)
                body = error.read()
            except (OSError, URLError) as error:
                status = 502
                body = json.dumps({
                    "error": {"category": "LabProxyError", "message": str(error)}
                }).encode("utf-8")
            capture["status"] = status
            capture["body"] = body
            self.send_response(status)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, format: str, *args: Any) -> None:
            return

    server = ThreadingHTTPServer(("127.0.0.1", 0), RecordingProxy)
    server.timeout = 50
    proxy_port = int(server.server_address[1])
    state["ai_port"] = proxy_port
    thread = threading.Thread(target=server.handle_request, daemon=True)
    thread.start()
    try:
        option = "--explain" if mode == "explain" else "--advise"
        result = _cli(state, report, "diagnose", option)
    finally:
        thread.join(timeout=1)
        server.server_close()
        state.pop("ai_port", None)
    if "body" not in capture:
        raise LabError("weaknetctl did not issue the expected AI runtime request")
    try:
        payload = json.loads(bytes(capture["body"]).decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise LabError(f"AI runtime response is not valid JSON: {error}") from error
    if not isinstance(payload, dict):
        raise LabError("AI runtime response is not an object")
    return result, int(capture["status"]), payload


def _hypothesis_signature(items: Any) -> list[tuple[str, str]]:
    if not isinstance(items, list):
        return []
    result: list[tuple[str, str]] = []
    for item in items:
        if isinstance(item, Mapping):
            result.append((str(item.get("type", "")), str(item.get("confidence", ""))))
    return sorted(result)


def _run_ai(
    state: dict[str, Any], report: CapabilityReport, run_root: Path,
    mode: str, deterministic_cli: subprocess.CompletedProcess[str], diagnosis: Mapping[str, Any],
) -> dict[str, Any]:
    if mode == "none":
        return {"attempted": False}
    started, reason = _start_ai_runtime(state, report, run_root)
    if not started:
        return {"attempted": False, "mode": mode, "status": "SKIP", "reason": reason}
    result, http_status, payload = _run_cli_with_ai_capture(state, report, mode)
    (run_root / f"weaknetctl-{mode}.txt").write_text(
        result.stdout + result.stderr, encoding="utf-8"
    )
    _atomic_json(run_root / f"ai-{mode}-report.json", payload)
    status_unchanged = payload.get("deterministic_status") == diagnosis.get("status")
    report_signature = _hypothesis_signature(payload.get("hypotheses"))
    diagnosis_signature = _hypothesis_signature(diagnosis.get("hypotheses"))
    type_unchanged = [item[0] for item in report_signature] == [item[0] for item in diagnosis_signature]
    confidence_unchanged = report_signature == diagnosis_signature
    deterministic_exit_unchanged = result.returncode == deterministic_cli.returncode
    if mode == "explain":
        schema_success = http_status == 200 and payload.get("validation_status") == "validated"
        grounded = schema_success and status_unchanged and type_unchanged and confidence_unchanged
        success = grounded and deterministic_exit_unchanged
        return {
            "attempted": True,
            "mode": mode,
            "status": "PASS" if success else "FAIL",
            "schema_success": schema_success,
            "diagnosis_grounding": grounded,
            "authoritative_type_unchanged": type_unchanged,
            "confidence_unchanged": confidence_unchanged,
            "deterministic_exit_unchanged": deterministic_exit_unchanged,
        }
    retrieval_mode = str(payload.get("retrieval_mode", "none"))
    report_status = str(payload.get("status", ""))
    schema_success = http_status == 200 and report_status in {"validated", "not_applicable"}
    invalid_citations = int(payload.get("invalid_citation_count", 0))
    grounding_violations = int(payload.get("grounding_violation_count", 0))
    schema_failures = int(payload.get("schema_failure_count", 0))
    citation_grounding = schema_success and invalid_citations == 0
    diagnosis_grounding = (
        schema_success and grounding_violations == 0 and status_unchanged
        and type_unchanged and confidence_unchanged
    )
    success = (
        diagnosis_grounding and citation_grounding and schema_failures == 0
        and deterministic_exit_unchanged
    )
    return {
        "attempted": True,
        "mode": mode,
        "status": "PASS" if success else "FAIL",
        "report_status": report_status,
        "schema_success": schema_success and schema_failures == 0,
        "diagnosis_grounding": diagnosis_grounding,
        "citation_grounding": citation_grounding,
        "invalid_citation_count": invalid_citations,
        "uncited_knowledge_claim_count": grounding_violations,
        "forbidden_overclaim_count": grounding_violations,
        "authoritative_type_unchanged": type_unchanged,
        "confidence_unchanged": confidence_unchanged,
        "deterministic_exit_unchanged": deterministic_exit_unchanged,
        "retrieval_mode": retrieval_mode,
    }


def _resources_present(resources: ResourceNames) -> bool:
    try:
        namespace_result = run_bounded(["ip", "netns", "list"], check=False, timeout=5)
    except (OSError, LabError):
        return True
    namespaces = {line.split()[0] for line in namespace_result.stdout.splitlines() if line.split()}
    if resources.client_namespace in namespaces or resources.server_namespace in namespaces:
        return True
    for interface in (resources.client_interface, resources.server_interface):
        try:
            if run_bounded(
                ["ip", "link", "show", "dev", interface], check=False, timeout=5,
            ).returncode == 0:
                return True
        except (OSError, LabError):
            return True
    return False


def cleanup_lab(
    state_path: Path = ACTIVE_STATE, *, report: CapabilityReport | None = None,
) -> list[str]:
    state = _load_state(state_path)
    if state is None:
        return []
    resources = ResourceNames.from_state(state["resources"])
    actions: list[str] = []
    for name in ("ai_runtime", "tcp_load", "weaknetd", "tcp_server", "dbus"):
        record = state.get("processes", {}).get(name)
        if isinstance(record, Mapping):
            _stop_owned_process(record)
            actions.append(f"stopped {name}")
    capability_report = report or detect_capabilities(ROOT)
    if capability_report.privileged:
        prefix = _privilege_prefix(capability_report)
        for namespace in (resources.client_namespace, resources.server_namespace):
            run_bounded([*prefix, "ip", "netns", "del", namespace], check=False, timeout=10)
            actions.append(f"removed {namespace}")
        for interface in (resources.client_interface, resources.server_interface):
            run_bounded([*prefix, "ip", "link", "del", interface], check=False, timeout=10)
    else:
        actions.append("network cleanup requires privilege")
    if not _resources_present(resources):
        try:
            state_path.unlink()
        except FileNotFoundError:
            pass
    else:
        actions.append("retained state for cleanup retry")
    for action in actions:
        _debug(action)
    return actions


def _new_state(scenario: Scenario) -> tuple[dict[str, Any], Path]:
    if ACTIVE_STATE.exists():
        raise LabError("a lab is already active; run './lab/weaknet-lab down' first")
    resources = ResourceNames.create()
    run_id = f"{scenario.scenario_id}-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{resources.token}"
    run_root = OUTPUT_ROOT / run_id
    run_root.mkdir(parents=True, exist_ok=False)
    state: dict[str, Any] = {
        "schema_version": "weaknet.lab.state.v1",
        "run_id": run_id,
        "scenario": scenario.scenario_id,
        "created_at": utc_now(),
        "resources": resources.to_dict(),
        "run_root": str(run_root.resolve()),
        "processes": {},
        "phase": "allocating",
    }
    _atomic_json(ACTIVE_STATE, state)
    _debug(f"allocated run {run_id} at {run_root}")
    _debug(
        f"resources: {resources.client_namespace}, {resources.server_namespace}, "
        f"{resources.client_interface}, {resources.server_interface}"
    )
    return state, run_root


def _bring_up(scenario: Scenario, report: CapabilityReport) -> tuple[dict[str, Any], Path]:
    state, run_root = _new_state(scenario)
    _start_bus(state, run_root)
    _setup_topology(state, report)
    _start_product(state, report, run_root)
    if scenario.workload == "tcp-echo":
        _start_workload(state, report, run_root)
    state["phase"] = "warmup"
    _atomic_json(ACTIVE_STATE, state)
    if scenario.warmup_seconds:
        time.sleep(scenario.warmup_seconds)
    _apply_fault(state, report, scenario)
    state["phase"] = "fault-active"
    state["fault_activated_at"] = utc_now()
    _atomic_json(ACTIVE_STATE, state)
    return state, run_root


def _write_result(run_root: Path, result: Mapping[str, Any]) -> None:
    validate_evaluation(result)
    _atomic_json(run_root / "evaluation.json", result)


def _print_result(result: Mapping[str, Any]) -> None:
    print(f"[scenario] {result['scenario']}")
    print(f"[setup] {result['setup'].upper()}")
    if result["result"] == "SKIP":
        print(f"[result] SKIP: {', '.join(result.get('skip_reasons', []))}")
        return
    for incident in result["observed_incidents"]:
        print(f"[incident] {incident}")
    for hypothesis in result["observed_hypotheses"]:
        print(f"[root cause] {hypothesis}")
    print(f"[status] {result['status']}")
    if result["detection_latency_ms"] is not None:
        print(f"[detection] {result['detection_latency_ms'] / 1000:.1f}s")
    if result["recovered"] is not None:
        label = "PASS" if result["recovered"] else "FAIL"
        detail = f" in {result['recovery_latency_ms'] / 1000:.1f}s" if result["recovery_latency_ms"] is not None else ""
        print(f"[recovery] {label}{detail}")
    ai = result["ai"]
    print(f"[ai] {ai.get('status', 'disabled') if ai.get('attempted') else ai.get('status', 'disabled')}")
    print(f"[result] {result['result']}")


def command_list(_: argparse.Namespace) -> int:
    for scenario in scenarios():
        print(f"{scenario.scenario_id:22} {scenario.title}")
    return 0


def command_doctor(_: argparse.Namespace) -> int:
    report = detect_capabilities(ROOT)
    for line in public_doctor_lines(report):
        print(line)
    if not report.netns:
        print("scenarios: SKIP until namespace privileges are available")
    elif not all((report.weaknetd, report.weaknetctl, report.dbus_next)):
        print("scenarios: SKIP until binaries and runtime dependencies are available")
    else:
        print("scenarios: ready")
    return 0


def command_up(arguments: argparse.Namespace) -> int:
    scenario = load_scenario(_scenario_path(arguments.scenario))
    report = detect_capabilities(ROOT)
    missing = missing_capabilities(scenario, report)
    if missing:
        print(f"SKIP: missing capabilities: {', '.join(missing)}")
        return 77
    try:
        state, _ = _bring_up(scenario, report)
    except KeyboardInterrupt:
        cleanup_lab(report=report)
        raise
    except Exception:
        cleanup_lab(report=report)
        raise
    print(f"lab up: {scenario.scenario_id} ({state['run_id']})")
    return 0


def command_status(_: argparse.Namespace) -> int:
    state = _load_state()
    if state is None:
        print("lab status: down")
        return 0
    diagnosis = _capture_diagnosis(state)
    print(f"lab status: {state.get('phase', 'unknown')}")
    print(f"scenario: {state['scenario']}")
    print(f"diagnosis: {diagnosis['status']}")
    print("incidents: " + ", ".join(item["type"] for item in diagnosis["incidents"]))
    print("hypotheses: " + ", ".join(item["type"] for item in diagnosis["hypotheses"]))
    return 0


def command_down(_: argparse.Namespace) -> int:
    actions = cleanup_lab()
    print("lab down" if actions else "lab already down")
    return 0


def command_run(arguments: argparse.Namespace) -> int:
    scenario = load_scenario(_scenario_path(arguments.scenario))
    report = detect_capabilities(ROOT)
    run_id = f"{scenario.scenario_id}-skip-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
    missing = missing_capabilities(scenario, report)
    if missing:
        result = skipped_evaluation(scenario, run_id, [f"missing capability: {item}" for item in missing])
        run_root = OUTPUT_ROOT / run_id
        run_root.mkdir(parents=True, exist_ok=True)
        _write_result(run_root, result)
        _print_result(result)
        return 0
    state: dict[str, Any] | None = None
    try:
        state, run_root = _bring_up(scenario, report)
        diagnosis, latency = _wait_for_diagnosis(state, scenario)
        deterministic_cli = _cli(state, report, "diagnose")
        (run_root / "weaknetctl-diagnose.txt").write_text(
            deterministic_cli.stdout + deterministic_cli.stderr, encoding="utf-8"
        )
        ai = _run_ai(
            state, report, run_root, arguments.ai_mode, deterministic_cli, diagnosis,
        )
        recovered: bool | None = None
        recovery_latency: int | None = None
        if scenario.recovery:
            _remove_fault(state, report, scenario)
            state["phase"] = "recovering"
            _atomic_json(ACTIVE_STATE, state)
            recovered, recovery_latency = _wait_for_recovery(state, scenario)
        result = evaluate_diagnosis(
            scenario, diagnosis, detection_latency_ms=latency,
            recovered=recovered, recovery_latency_ms=recovery_latency,
            run_id=state["run_id"], ai=ai,
        )
        _write_result(run_root, result)
        _print_result(result)
        return 0 if result["result"] == "PASS" else 1
    except (LabError, ValueError) as error:
        print(f"[result] FAIL: {error}", file=sys.stderr)
        return 1
    finally:
        if state is not None or ACTIVE_STATE.exists():
            cleanup_lab(report=report)


def command_fixture_demo(arguments: argparse.Namespace) -> int:
    from ai.tests.fixtures import local_link_suspected
    from ai.v2.providers.fake import FakeLlmProvider
    print("SIMULATION: canonical DiagnosisSnapshot fixture; not real Linux telemetry")
    snapshot = local_link_suspected()
    if arguments.mode == "explain":
        from ai.v2.services.explainer import EvidenceExplainerService
        report = EvidenceExplainerService(FakeLlmProvider()).explain_sync(snapshot, "lab-fixture")
        print(json.dumps({
            "simulation": True,
            "mode": "explain",
            "schema_success": report.validation_status == "validated",
            "authoritative_type_unchanged": report.hypotheses[0].type == snapshot.hypotheses[0].type,
            "confidence_unchanged": report.hypotheses[0].confidence == snapshot.hypotheses[0].confidence,
        }, indent=2, sort_keys=True))
    else:
        from ai.v2.services.advisor import RagAdvisorService
        report = RagAdvisorService(FakeLlmProvider()).advise_sync(snapshot, request_id="lab-fixture")
        print(json.dumps({
            "simulation": True,
            "mode": "advise",
            "schema_success": report.status == "validated",
            "diagnosis_grounding": report.grounding_violation_count == 0,
            "citation_grounding": report.invalid_citation_count == 0,
            "retrieval_mode": report.retrieval_mode,
            "authoritative_type_unchanged": report.hypotheses[0]["type"] == snapshot.hypotheses[0].type,
            "confidence_unchanged": report.hypotheses[0]["confidence"] == snapshot.hypotheses[0].confidence,
        }, indent=2, sort_keys=True))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="weaknet-lab")
    parser.add_argument("--verbose", action="store_true", help="show additional orchestration details")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("list", help="list available scenarios").set_defaults(handler=command_list)
    subparsers.add_parser("doctor", help="report lab prerequisites without exposing secrets").set_defaults(handler=command_doctor)
    up = subparsers.add_parser("up", help="create and leave a scenario running")
    up.add_argument("scenario")
    up.set_defaults(handler=command_up)
    subparsers.add_parser("status", help="show active lab state").set_defaults(handler=command_status)
    run = subparsers.add_parser("run", help="run, evaluate, and clean up a scenario")
    run.add_argument("scenario")
    ai = run.add_mutually_exclusive_group()
    ai.add_argument("--explain", dest="ai_mode", action="store_const", const="explain")
    ai.add_argument("--advise", dest="ai_mode", action="store_const", const="advise")
    ai.add_argument("--no-ai", dest="ai_mode", action="store_const", const="none")
    run.set_defaults(handler=command_run, ai_mode="none")
    subparsers.add_parser("down", help="remove only the active lab's resources").set_defaults(handler=command_down)
    subparsers.add_parser("cleanup", help="idempotent alias for down").set_defaults(handler=command_down)
    fixture = subparsers.add_parser("fixture-demo", help="run a clearly labeled offline AI simulation")
    fixture.add_argument("--mode", choices=("explain", "advise"), default="advise")
    fixture.set_defaults(handler=command_fixture_demo)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    global VERBOSE
    parser = build_parser()
    arguments = parser.parse_args(argv)
    VERBOSE = bool(arguments.verbose)
    if getattr(arguments, "ai_mode", "none") not in AI_MODES:
        parser.error("invalid AI mode")
    try:
        return int(arguments.handler(arguments))
    except KeyboardInterrupt:
        print("weaknet-lab: interrupted", file=sys.stderr)
        return 130
    except (LabError, ValueError) as error:
        print(f"weaknet-lab: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
